/* Runtime asset contract. Ordered classic scripts: do not alphabetise.
 * Shared by the browser loader, service worker and validation tools. */
globalThis.RT_ASSETS = Object.freeze({
  "build": "20260924-v1569-staging",
  "environment": "staging",
  "entry": [
    "src/domain/accounting-engine.js",
    "src/domain/report-engine.js"
  ],
  "core": "src/core/application.js",
  "launch": "src/platform/launch.js",
  "critical": [
    "src/platform/performance.js",
    "src/platform/navigation.js",
    "src/platform/lifecycle.js",
    "src/features/charts/polish.js",
    "src/features/charts/motion.js",
    "src/features/charts/finalize.js",
    "src/features/charts/reveal.js",
    "src/platform/interface-motion.js"
  ],
  "deferred": [
    "src/platform/staging-auth.js",
    "src/features/sales/defaults.js",
    "src/features/bundles/orders.js",
    "src/features/bundles/panel.js",
    "src/features/bundles/row-polish.js",
    "src/features/cashflow/liabilities.js",
    "src/domain/relist-fees.js",
    "src/features/partners/detail-stability.js",
    "src/features/cashflow/dashboard-v2.js",
    "src/features/cashflow/movement-card-polish.js",
    "src/features/cashflow/performance-v1509.js",
    "src/features/partners/item-navigation.js",
    "src/features/partners/actions-v2.js",
    "src/features/partners/statement-action.js",
    "src/features/partners/account-ui-v3.js",
    "src/features/partners/account-ui-v4.js",
    "src/features/partners/account-cleanup.js",
    "src/features/partners/row-menu-popover.js",
    "src/features/partners/item-adjustments.js",
    "src/features/partners/arrangements-v2.js",
    "src/features/partners/account-finalise.js",
    "src/features/partners/account-legacy-hero-cleanup.js",
    "src/features/partners/account-adjustments.js",
    "src/features/partners/account-adjustments-hardening.js",
    "src/features/partners/payment-allocations-v2.js",
    "src/features/partners/account-transaction-ui.js",
    "src/features/partners/transaction-breakdown-guard.js",
    "src/features/partners/collapse-defaults.js",
    "src/features/partners/operations-dashboard.js",
    "src/features/partners/sort-polish.js",
    "src/features/partners/operations-compact-v2.js",
    "src/features/partners/account-experience-v2.js",
    "src/features/partners/page-unified-v1503.js",
    "src/features/sales/calendar-layout-v1530.js",
    "src/features/exports/documents.js",
    "src/features/sales/chart-sequence.js"
  ],
  "lazy": [
    "src/features/partners/statements.js",
    "src/features/partners/statements-accounting-v3.js",
    "src/features/partners/account-adjustment-statements.js",
    "src/features/diagnostics/preview-fixtures.js",
    "src/features/diagnostics/accounting-fixtures.js"
  ],
  "bindings": [
    "src/platform/staging-binding.js"
  ],
  "styles": [
    "assets/styles/application.css",
    "assets/styles/loading.css"
  ],
  "icons": [
    "assets/icons/app-180.png",
    "assets/icons/app-32.png"
  ],
  "launchImages": [
    "assets/launch/launch-light-1206x2622.png",
    "assets/launch/launch-light-1284x2778.png",
    "assets/launch/launch-light-1179x2556.png",
    "assets/launch/launch-dark-1170x2532.png",
    "assets/launch/launch-dark-1320x2868.png",
    "assets/launch/launch-dark-1290x2796.png",
    "assets/launch/launch-dark-1284x2778.png",
    "assets/launch/launch-light-1170x2532.png",
    "assets/launch/launch-dark-1179x2556.png",
    "assets/launch/launch-light-1320x2868.png",
    "assets/launch/launch-light-1290x2796.png",
    "assets/launch/launch-dark-1206x2622.png"
  ],
  "legacy": {
    "app-core.js": "src/core/application.js",
    "accounting.js": "src/domain/accounting-engine.js",
    "reports.js": "src/domain/report-engine.js",
    "launch-experience.js": "src/platform/launch.js",
    "performance-system.js": "src/platform/performance.js",
    "navigation-stability.js": "src/platform/navigation.js",
    "app-lifecycle.js": "src/platform/lifecycle.js",
    "motion-system.js": "src/platform/interface-motion.js",
    "account-detail-stability.js": "src/features/partners/detail-stability.js",
    "item-account-adjustments.js": "src/features/partners/item-adjustments.js",
    "relist-fee-integrity.js": "src/domain/relist-fees.js",
    "document-exports.js": "src/features/exports/documents.js",
    "app.css": "assets/styles/application.css",
    "skeleton-motion-polish-v1512.css": "assets/styles/loading.css",
    "icon-180.png": "assets/icons/app-180.png",
    "icon-32.png": "assets/icons/app-32.png",
    "partner-account-adjustment-statements.js": "src/features/partners/account-adjustment-statements.js",
    "partner-statement-action.js": "src/features/partners/statement-action.js",
    "accounts-sort-polish.js": "src/features/partners/sort-polish.js",
    "partner-account-ui-v4.js": "src/features/partners/account-ui-v4.js",
    "partner-payment-allocations-v2.js": "src/features/partners/payment-allocations-v2.js",
    "partner-account-ui-v3.js": "src/features/partners/account-ui-v3.js",
    "cashflow-liabilities.js": "src/features/cashflow/liabilities.js",
    "partner-row-menu-popover.js": "src/features/partners/row-menu-popover.js",
    "sales-chart-sequence.js": "src/features/sales/chart-sequence.js",
    "partner-collapse-defaults.js": "src/features/partners/collapse-defaults.js",
    "partner-statements-accounting-v3.js": "src/features/partners/statements-accounting-v3.js",
    "cashflow-performance-v1509.js": "src/features/cashflow/performance-v1509.js",
    "accounts-operations-compact-v2.js": "src/features/partners/operations-compact-v2.js",
    "partner-item-navigation.js": "src/features/partners/item-navigation.js",
    "partner-arrangements-v2.js": "src/features/partners/arrangements-v2.js",
    "partner-account-experience-v2.js": "src/features/partners/account-experience-v2.js",
    "chart-finalize.js": "src/features/charts/finalize.js",
    "accounts-operations-dashboard.js": "src/features/partners/operations-dashboard.js",
    "bundle-row-polish.js": "src/features/bundles/row-polish.js",
    "partner-account-finalise.js": "src/features/partners/account-finalise.js",
    "chart-polish.js": "src/features/charts/polish.js",
    "chart-motion.js": "src/features/charts/motion.js",
    "partner-actions-v2.js": "src/features/partners/actions-v2.js",
    "partner-account-legacy-hero-cleanup.js": "src/features/partners/account-legacy-hero-cleanup.js",
    "bundle-orders.js": "src/features/bundles/orders.js",
    "partner-page-unified-v1503.js": "src/features/partners/page-unified-v1503.js",
    "cashflow-dashboard-v2.js": "src/features/cashflow/dashboard-v2.js",
    "chart-reveal.js": "src/features/charts/reveal.js",
    "partner-account-transaction-ui.js": "src/features/partners/account-transaction-ui.js",
    "bundle-panel.js": "src/features/bundles/panel.js",
    "partner-transaction-breakdown-guard.js": "src/features/partners/transaction-breakdown-guard.js",
    "partner-account-adjustments-hardening.js": "src/features/partners/account-adjustments-hardening.js",
    "partner-account-cleanup.js": "src/features/partners/account-cleanup.js",
    "sales-calendar-layout-v1530.js": "src/features/sales/calendar-layout-v1530.js",
    "partner-account-adjustments.js": "src/features/partners/account-adjustments.js",
    "cashflow-movement-card-polish.js": "src/features/cashflow/movement-card-polish.js",
    "sales-defaults.js": "src/features/sales/defaults.js",
    "partner-statements.js": "src/features/partners/statements.js",
    "launch-light-1206x2622.png": "assets/launch/launch-light-1206x2622.png",
    "launch-light-1284x2778.png": "assets/launch/launch-light-1284x2778.png",
    "launch-light-1179x2556.png": "assets/launch/launch-light-1179x2556.png",
    "launch-dark-1170x2532.png": "assets/launch/launch-dark-1170x2532.png",
    "launch-dark-1320x2868.png": "assets/launch/launch-dark-1320x2868.png",
    "launch-dark-1290x2796.png": "assets/launch/launch-dark-1290x2796.png",
    "launch-dark-1284x2778.png": "assets/launch/launch-dark-1284x2778.png",
    "launch-light-1170x2532.png": "assets/launch/launch-light-1170x2532.png",
    "launch-dark-1179x2556.png": "assets/launch/launch-dark-1179x2556.png",
    "launch-light-1320x2868.png": "assets/launch/launch-light-1320x2868.png",
    "launch-light-1290x2796.png": "assets/launch/launch-light-1290x2796.png",
    "launch-dark-1206x2622.png": "assets/launch/launch-dark-1206x2622.png",
    "staging-supabase.js": "src/platform/staging-binding.js",
    "staging-dev-auth.js": "src/platform/staging-auth.js"
  }
});
